{
  "formatVersion": "1.1",
  "component": {
    "group": "io.karte.android",
    "module": "notifications",
    "version": "2.9.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "2oj54mwsnvc35kadvzykizezu4"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.karte.android",
          "module": "core",
          "version": {
            "requires": "2.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "notifications-2.9.4.aar",
          "url": "notifications-2.9.4.aar",
          "size": 76428,
          "sha512": "5c61d710ebda478299be77c5df1622de4c9eaa3fa37c62da5cd07dcf4fa44d28342461f7c616e05dbdc59bbf5838af32f6db2b714a0c1735fa1cd1099558aad7",
          "sha256": "4e66ee2af5161c97bc1f63c939c9ad8e767b46ed24d5fe2360326d5054d3dd9b",
          "sha1": "1a6cca30920f4e983dc1ad27069bfda22dfb7018",
          "md5": "000bda203bd26d0865e98737fe5e39a0"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging",
          "version": {
            "requires": "19.0.0"
          }
        },
        {
          "group": "io.karte.android",
          "module": "core",
          "version": {
            "requires": "2.20.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.3.50"
          }
        }
      ],
      "files": [
        {
          "name": "notifications-2.9.4.aar",
          "url": "notifications-2.9.4.aar",
          "size": 76428,
          "sha512": "5c61d710ebda478299be77c5df1622de4c9eaa3fa37c62da5cd07dcf4fa44d28342461f7c616e05dbdc59bbf5838af32f6db2b714a0c1735fa1cd1099558aad7",
          "sha256": "4e66ee2af5161c97bc1f63c939c9ad8e767b46ed24d5fe2360326d5054d3dd9b",
          "sha1": "1a6cca30920f4e983dc1ad27069bfda22dfb7018",
          "md5": "000bda203bd26d0865e98737fe5e39a0"
        }
      ]
    }
  ]
}
